version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ALLOWED_IDS=${ALLOWED_IDS}
      - CONFIG_FILE=${CONFIG_FILE}
#Synology connection details
      - SYNOLOGY_BASE_API_URL=${SYNOLOGY_BASE_API_URL}
      - USER=${USER}
      - PASS=${PASS}
      - CHAT_ID=${CHAT_ID}

    volumes:
      - "./data:/data"
      - "./config:/config"
      - "./gifs:/gifs"
    restart: always
