version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CONFIG_FILE=${CONFIG_FILE}
      - ALLOWED_IDS= ${ALLOWED_IDS}
    volumes:
      - "./data:/data"
      - "./config:/config"
      - "./gifs:/gifs"
    restart: always
